# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qvibeplot.ui'
#
# Created: Wed Nov 19 22:48:54 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(757, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.leftVLayout = QtGui.QVBoxLayout()
        self.leftVLayout.setObjectName(_fromUtf8("leftVLayout"))
        self.moleculeGB = QtGui.QGroupBox(self.centralwidget)
        self.moleculeGB.setObjectName(_fromUtf8("moleculeGB"))
        self.formLayout_3 = QtGui.QFormLayout(self.moleculeGB)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.fontSizeLabel = QtGui.QLabel(self.moleculeGB)
        self.fontSizeLabel.setObjectName(_fromUtf8("fontSizeLabel"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.fontSizeLabel)
        self.fontSizeComboBox = QtGui.QComboBox(self.moleculeGB)
        self.fontSizeComboBox.setObjectName(_fromUtf8("fontSizeComboBox"))
        self.fontSizeComboBox.addItem(_fromUtf8(""))
        self.fontSizeComboBox.setItemText(0, _fromUtf8("6"))
        self.fontSizeComboBox.addItem(_fromUtf8(""))
        self.fontSizeComboBox.setItemText(1, _fromUtf8("8"))
        self.fontSizeComboBox.addItem(_fromUtf8(""))
        self.fontSizeComboBox.setItemText(2, _fromUtf8("10"))
        self.fontSizeComboBox.addItem(_fromUtf8(""))
        self.fontSizeComboBox.setItemText(3, _fromUtf8("12"))
        self.fontSizeComboBox.addItem(_fromUtf8(""))
        self.fontSizeComboBox.setItemText(4, _fromUtf8("14"))
        self.fontSizeComboBox.addItem(_fromUtf8(""))
        self.fontSizeComboBox.setItemText(5, _fromUtf8("18"))
        self.fontSizeComboBox.addItem(_fromUtf8(""))
        self.fontSizeComboBox.setItemText(6, _fromUtf8("20"))
        self.fontSizeComboBox.addItem(_fromUtf8(""))
        self.fontSizeComboBox.setItemText(7, _fromUtf8("24"))
        self.fontSizeComboBox.addItem(_fromUtf8(""))
        self.fontSizeComboBox.setItemText(8, _fromUtf8("32"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.fontSizeComboBox)
        self.lineWidthLabel = QtGui.QLabel(self.moleculeGB)
        self.lineWidthLabel.setObjectName(_fromUtf8("lineWidthLabel"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.lineWidthLabel)
        self.lineWidthComboBox = QtGui.QComboBox(self.moleculeGB)
        self.lineWidthComboBox.setObjectName(_fromUtf8("lineWidthComboBox"))
        self.lineWidthComboBox.addItem(_fromUtf8(""))
        self.lineWidthComboBox.addItem(_fromUtf8(""))
        self.lineWidthComboBox.addItem(_fromUtf8(""))
        self.lineWidthComboBox.addItem(_fromUtf8(""))
        self.lineWidthComboBox.addItem(_fromUtf8(""))
        self.lineWidthComboBox.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineWidthComboBox)
        self.colorLabelLabel = QtGui.QLabel(self.moleculeGB)
        self.colorLabelLabel.setObjectName(_fromUtf8("colorLabelLabel"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.colorLabelLabel)
        self.colorLabelCheckBox = QtGui.QCheckBox(self.moleculeGB)
        self.colorLabelCheckBox.setEnabled(True)
        self.colorLabelCheckBox.setText(_fromUtf8(""))
        self.colorLabelCheckBox.setObjectName(_fromUtf8("colorLabelCheckBox"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.colorLabelCheckBox)
        self.leftVLayout.addWidget(self.moleculeGB)
        self.vibrationGB = QtGui.QGroupBox(self.centralwidget)
        self.vibrationGB.setObjectName(_fromUtf8("vibrationGB"))
        self.formLayout_2 = QtGui.QFormLayout(self.vibrationGB)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.bondlengthFilterLabel = QtGui.QLabel(self.vibrationGB)
        self.bondlengthFilterLabel.setObjectName(_fromUtf8("bondlengthFilterLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.bondlengthFilterLabel)
        self.bondlengthFilter = QtGui.QSpinBox(self.vibrationGB)
        self.bondlengthFilter.setSuffix(_fromUtf8(" pm"))
        self.bondlengthFilter.setMaximum(100)
        self.bondlengthFilter.setSingleStep(5)
        self.bondlengthFilter.setProperty("value", 0)
        self.bondlengthFilter.setObjectName(_fromUtf8("bondlengthFilter"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.bondlengthFilter)
        self.angleFilterLabel = QtGui.QLabel(self.vibrationGB)
        self.angleFilterLabel.setObjectName(_fromUtf8("angleFilterLabel"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.angleFilterLabel)
        self.angleFilter = QtGui.QSpinBox(self.vibrationGB)
        self.angleFilter.setMaximum(90)
        self.angleFilter.setSingleStep(5)
        self.angleFilter.setProperty("value", 0)
        self.angleFilter.setObjectName(_fromUtf8("angleFilter"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.angleFilter)
        self.torsionFilterLabel = QtGui.QLabel(self.vibrationGB)
        self.torsionFilterLabel.setObjectName(_fromUtf8("torsionFilterLabel"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.torsionFilterLabel)
        self.torsionFilter = QtGui.QSpinBox(self.vibrationGB)
        self.torsionFilter.setMaximum(180)
        self.torsionFilter.setSingleStep(10)
        self.torsionFilter.setProperty("value", 0)
        self.torsionFilter.setObjectName(_fromUtf8("torsionFilter"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.torsionFilter)
        self.leftVLayout.addWidget(self.vibrationGB)
        self.spectrumGB = QtGui.QGroupBox(self.centralwidget)
        self.spectrumGB.setObjectName(_fromUtf8("spectrumGB"))
        self.formLayout = QtGui.QFormLayout(self.spectrumGB)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.broadeningLabel = QtGui.QLabel(self.spectrumGB)
        self.broadeningLabel.setObjectName(_fromUtf8("broadeningLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.broadeningLabel)
        self.broadeningComboBox = QtGui.QComboBox(self.spectrumGB)
        self.broadeningComboBox.setObjectName(_fromUtf8("broadeningComboBox"))
        self.broadeningComboBox.addItem(_fromUtf8(""))
        self.broadeningComboBox.addItem(_fromUtf8(""))
        self.broadeningComboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.broadeningComboBox)
        self.fwhmLabel = QtGui.QLabel(self.spectrumGB)
        self.fwhmLabel.setObjectName(_fromUtf8("fwhmLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.fwhmLabel)
        self.fwhmDoubleSpinBox = QtGui.QDoubleSpinBox(self.spectrumGB)
        self.fwhmDoubleSpinBox.setDecimals(1)
        self.fwhmDoubleSpinBox.setMaximum(40.0)
        self.fwhmDoubleSpinBox.setProperty("value", 8.0)
        self.fwhmDoubleSpinBox.setObjectName(_fromUtf8("fwhmDoubleSpinBox"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.fwhmDoubleSpinBox)
        self.leftVLayout.addWidget(self.spectrumGB)
        self.frequencyList = QtGui.QListWidget(self.centralwidget)
        self.frequencyList.setObjectName(_fromUtf8("frequencyList"))
        self.leftVLayout.addWidget(self.frequencyList)
        self.horizontalLayout.addLayout(self.leftVLayout)
        self.rightVLayout = QtGui.QVBoxLayout()
        self.rightVLayout.setObjectName(_fromUtf8("rightVLayout"))
        self.moleculeCanvas = MplCanvas(self.centralwidget)
        self.moleculeCanvas.setMinimumSize(QtCore.QSize(200, 200))
        self.moleculeCanvas.setObjectName(_fromUtf8("moleculeCanvas"))
        self.rightVLayout.addWidget(self.moleculeCanvas)
        self.spectrumCanvas = MplCanvas(self.centralwidget)
        self.spectrumCanvas.setObjectName(_fromUtf8("spectrumCanvas"))
        self.rightVLayout.addWidget(self.spectrumCanvas)
        self.horizontalLayout.addLayout(self.rightVLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 757, 19))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.fileMenu = QtGui.QMenu(self.menuBar)
        self.fileMenu.setObjectName(_fromUtf8("fileMenu"))
        self.viewMenu = QtGui.QMenu(self.menuBar)
        self.viewMenu.setObjectName(_fromUtf8("viewMenu"))
        self.helpMenu = QtGui.QMenu(self.menuBar)
        self.helpMenu.setObjectName(_fromUtf8("helpMenu"))
        MainWindow.setMenuBar(self.menuBar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.openAction = QtGui.QAction(MainWindow)
        self.openAction.setObjectName(_fromUtf8("openAction"))
        self.saveImageAction = QtGui.QAction(MainWindow)
        self.saveImageAction.setObjectName(_fromUtf8("saveImageAction"))
        self.saveImageAsAction = QtGui.QAction(MainWindow)
        self.saveImageAsAction.setObjectName(_fromUtf8("saveImageAsAction"))
        self.aboutOrbiMolAction = QtGui.QAction(MainWindow)
        self.aboutOrbiMolAction.setObjectName(_fromUtf8("aboutOrbiMolAction"))
        self.quitAction = QtGui.QAction(MainWindow)
        self.quitAction.setObjectName(_fromUtf8("quitAction"))
        self.showIndexAction = QtGui.QAction(MainWindow)
        self.showIndexAction.setCheckable(True)
        self.showIndexAction.setObjectName(_fromUtf8("showIndexAction"))
        self.showSkeletonAction = QtGui.QAction(MainWindow)
        self.showSkeletonAction.setObjectName(_fromUtf8("showSkeletonAction"))
        self.aboutOpenBabelAction = QtGui.QAction(MainWindow)
        self.aboutOpenBabelAction.setObjectName(_fromUtf8("aboutOpenBabelAction"))
        self.aboutAction = QtGui.QAction(MainWindow)
        self.aboutAction.setObjectName(_fromUtf8("aboutAction"))
        self.aboutMplAction = QtGui.QAction(MainWindow)
        self.aboutMplAction.setObjectName(_fromUtf8("aboutMplAction"))
        self.menuBar.addAction(self.fileMenu.menuAction())
        self.menuBar.addAction(self.viewMenu.menuAction())
        self.menuBar.addAction(self.helpMenu.menuAction())
        self.fontSizeLabel.setBuddy(self.fontSizeComboBox)
        self.lineWidthLabel.setBuddy(self.lineWidthComboBox)
        self.colorLabelLabel.setBuddy(self.colorLabelCheckBox)
        self.bondlengthFilterLabel.setBuddy(self.bondlengthFilter)
        self.angleFilterLabel.setBuddy(self.angleFilter)
        self.torsionFilterLabel.setBuddy(self.torsionFilter)
        self.broadeningLabel.setBuddy(self.broadeningComboBox)
        self.fwhmLabel.setBuddy(self.fwhmDoubleSpinBox)

        self.retranslateUi(MainWindow)
        self.fontSizeComboBox.setCurrentIndex(3)
        self.lineWidthComboBox.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "QVibeplot", None))
        self.moleculeGB.setTitle(_translate("MainWindow", "Molecule", None))
        self.fontSizeLabel.setText(_translate("MainWindow", "Font Size", None))
        self.lineWidthLabel.setText(_translate("MainWindow", "Linewidth", None))
        self.lineWidthComboBox.setItemText(0, _translate("MainWindow", "0.0", None))
        self.lineWidthComboBox.setItemText(1, _translate("MainWindow", "0.2", None))
        self.lineWidthComboBox.setItemText(2, _translate("MainWindow", "0.5", None))
        self.lineWidthComboBox.setItemText(3, _translate("MainWindow", "1.0", None))
        self.lineWidthComboBox.setItemText(4, _translate("MainWindow", "2.0", None))
        self.lineWidthComboBox.setItemText(5, _translate("MainWindow", "4.0", None))
        self.colorLabelLabel.setText(_translate("MainWindow", "Black Labels", None))
        self.vibrationGB.setTitle(_translate("MainWindow", "Vibration filter", None))
        self.bondlengthFilterLabel.setText(_translate("MainWindow", "Bondlength", None))
        self.angleFilterLabel.setText(_translate("MainWindow", "Angle", None))
        self.angleFilter.setSuffix(_translate("MainWindow", "º", None))
        self.torsionFilterLabel.setText(_translate("MainWindow", "Torsion", None))
        self.torsionFilter.setSuffix(_translate("MainWindow", "º", None))
        self.spectrumGB.setTitle(_translate("MainWindow", "Spectrum broadening", None))
        self.broadeningLabel.setText(_translate("MainWindow", "Function", None))
        self.broadeningComboBox.setItemText(0, _translate("MainWindow", "none", None))
        self.broadeningComboBox.setItemText(1, _translate("MainWindow", "lorentzian", None))
        self.broadeningComboBox.setItemText(2, _translate("MainWindow", "gaussian", None))
        self.fwhmLabel.setText(_translate("MainWindow", "FWHM", None))
        self.frequencyList.setSortingEnabled(True)
        self.fileMenu.setTitle(_translate("MainWindow", "File", None))
        self.viewMenu.setTitle(_translate("MainWindow", "View", None))
        self.helpMenu.setTitle(_translate("MainWindow", "Help", None))
        self.openAction.setText(_translate("MainWindow", "Open", None))
        self.saveImageAction.setText(_translate("MainWindow", "Save image", None))
        self.saveImageAsAction.setText(_translate("MainWindow", "Save image as...", None))
        self.aboutOrbiMolAction.setText(_translate("MainWindow", "About OrbiMol...", None))
        self.quitAction.setText(_translate("MainWindow", "Quit", None))
        self.showIndexAction.setText(_translate("MainWindow", "Show index", None))
        self.showSkeletonAction.setText(_translate("MainWindow", "Show skeleton", None))
        self.aboutOpenBabelAction.setText(_translate("MainWindow", "About Open Babel", None))
        self.aboutAction.setText(_translate("MainWindow", "About", None))
        self.aboutMplAction.setText(_translate("MainWindow", "About Matplotlib", None))

from mpl_canvas import MplCanvas
