# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rsc/ui/qvibeplot.ui'
#
# Created: Sun Nov 16 16:11:05 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(757, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.leftVLayout = QtGui.QVBoxLayout()
        self.leftVLayout.setObjectName(_fromUtf8("leftVLayout"))
        self.moleculeGB = QtGui.QGroupBox(self.centralwidget)
        self.moleculeGB.setObjectName(_fromUtf8("moleculeGB"))
        self.formLayout_3 = QtGui.QFormLayout(self.moleculeGB)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.fontSizeLabel = QtGui.QLabel(self.moleculeGB)
        self.fontSizeLabel.setObjectName(_fromUtf8("fontSizeLabel"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.fontSizeLabel)
        self.fontSizeComboBox = QtGui.QComboBox(self.moleculeGB)
        self.fontSizeComboBox.setObjectName(_fromUtf8("fontSizeComboBox"))
        self.fontSizeComboBox.addItem(_fromUtf8(""))
        self.fontSizeComboBox.setItemText(0, _fromUtf8("6"))
        self.fontSizeComboBox.addItem(_fromUtf8(""))
        self.fontSizeComboBox.setItemText(1, _fromUtf8("8"))
        self.fontSizeComboBox.addItem(_fromUtf8(""))
        self.fontSizeComboBox.setItemText(2, _fromUtf8("10"))
        self.fontSizeComboBox.addItem(_fromUtf8(""))
        self.fontSizeComboBox.setItemText(3, _fromUtf8("12"))
        self.fontSizeComboBox.addItem(_fromUtf8(""))
        self.fontSizeComboBox.setItemText(4, _fromUtf8("14"))
        self.fontSizeComboBox.addItem(_fromUtf8(""))
        self.fontSizeComboBox.setItemText(5, _fromUtf8("18"))
        self.fontSizeComboBox.addItem(_fromUtf8(""))
        self.fontSizeComboBox.setItemText(6, _fromUtf8("20"))
        self.fontSizeComboBox.addItem(_fromUtf8(""))
        self.fontSizeComboBox.setItemText(7, _fromUtf8("24"))
        self.fontSizeComboBox.addItem(_fromUtf8(""))
        self.fontSizeComboBox.setItemText(8, _fromUtf8("32"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.fontSizeComboBox)
        self.lineWidthLabel = QtGui.QLabel(self.moleculeGB)
        self.lineWidthLabel.setObjectName(_fromUtf8("lineWidthLabel"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.lineWidthLabel)
        self.lineWidthComboBox = QtGui.QComboBox(self.moleculeGB)
        self.lineWidthComboBox.setObjectName(_fromUtf8("lineWidthComboBox"))
        self.lineWidthComboBox.addItem(_fromUtf8(""))
        self.lineWidthComboBox.addItem(_fromUtf8(""))
        self.lineWidthComboBox.addItem(_fromUtf8(""))
        self.lineWidthComboBox.addItem(_fromUtf8(""))
        self.lineWidthComboBox.addItem(_fromUtf8(""))
        self.lineWidthComboBox.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineWidthComboBox)
        self.colorLabelLabel = QtGui.QLabel(self.moleculeGB)
        self.colorLabelLabel.setObjectName(_fromUtf8("colorLabelLabel"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.colorLabelLabel)
        self.colorLabelCheckBox = QtGui.QCheckBox(self.moleculeGB)
        self.colorLabelCheckBox.setEnabled(True)
        self.colorLabelCheckBox.setText(_fromUtf8(""))
        self.colorLabelCheckBox.setObjectName(_fromUtf8("colorLabelCheckBox"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.colorLabelCheckBox)
        self.leftVLayout.addWidget(self.moleculeGB)
        self.vibrationGB = QtGui.QGroupBox(self.centralwidget)
        self.vibrationGB.setObjectName(_fromUtf8("vibrationGB"))
        self.formLayout_2 = QtGui.QFormLayout(self.vibrationGB)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.scalingFactorLabel = QtGui.QLabel(self.vibrationGB)
        self.scalingFactorLabel.setObjectName(_fromUtf8("scalingFactorLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.scalingFactorLabel)
        self.scalingFactorSpinBox = QtGui.QSpinBox(self.vibrationGB)
        self.scalingFactorSpinBox.setMaximum(500)
        self.scalingFactorSpinBox.setSingleStep(5)
        self.scalingFactorSpinBox.setProperty("value", 10)
        self.scalingFactorSpinBox.setObjectName(_fromUtf8("scalingFactorSpinBox"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.scalingFactorSpinBox)
        self.thresholdLabel = QtGui.QLabel(self.vibrationGB)
        self.thresholdLabel.setObjectName(_fromUtf8("thresholdLabel"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.thresholdLabel)
        self.thresholdComboBox = QtGui.QComboBox(self.vibrationGB)
        self.thresholdComboBox.setObjectName(_fromUtf8("thresholdComboBox"))
        self.thresholdComboBox.addItem(_fromUtf8(""))
        self.thresholdComboBox.setItemText(0, _fromUtf8("0.0"))
        self.thresholdComboBox.addItem(_fromUtf8(""))
        self.thresholdComboBox.setItemText(1, _fromUtf8("0.1"))
        self.thresholdComboBox.addItem(_fromUtf8(""))
        self.thresholdComboBox.setItemText(2, _fromUtf8("0.2"))
        self.thresholdComboBox.addItem(_fromUtf8(""))
        self.thresholdComboBox.setItemText(3, _fromUtf8("1.0"))
        self.thresholdComboBox.addItem(_fromUtf8(""))
        self.thresholdComboBox.setItemText(4, _fromUtf8("2.5"))
        self.thresholdComboBox.addItem(_fromUtf8(""))
        self.thresholdComboBox.setItemText(5, _fromUtf8("5.0"))
        self.thresholdComboBox.addItem(_fromUtf8(""))
        self.thresholdComboBox.setItemText(6, _fromUtf8("10.0"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.thresholdComboBox)
        self.leftVLayout.addWidget(self.vibrationGB)
        self.spectrumGB = QtGui.QGroupBox(self.centralwidget)
        self.spectrumGB.setObjectName(_fromUtf8("spectrumGB"))
        self.formLayout = QtGui.QFormLayout(self.spectrumGB)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.broadeningLabel = QtGui.QLabel(self.spectrumGB)
        self.broadeningLabel.setObjectName(_fromUtf8("broadeningLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.broadeningLabel)
        self.broadeningComboBox = QtGui.QComboBox(self.spectrumGB)
        self.broadeningComboBox.setObjectName(_fromUtf8("broadeningComboBox"))
        self.broadeningComboBox.addItem(_fromUtf8(""))
        self.broadeningComboBox.addItem(_fromUtf8(""))
        self.broadeningComboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.broadeningComboBox)
        self.fwhmLabel = QtGui.QLabel(self.spectrumGB)
        self.fwhmLabel.setObjectName(_fromUtf8("fwhmLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.fwhmLabel)
        self.fwhmDoubleSpinBox = QtGui.QDoubleSpinBox(self.spectrumGB)
        self.fwhmDoubleSpinBox.setDecimals(1)
        self.fwhmDoubleSpinBox.setMaximum(40.0)
        self.fwhmDoubleSpinBox.setProperty("value", 8.0)
        self.fwhmDoubleSpinBox.setObjectName(_fromUtf8("fwhmDoubleSpinBox"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.fwhmDoubleSpinBox)
        self.leftVLayout.addWidget(self.spectrumGB)
        self.frequencyList = QtGui.QListWidget(self.centralwidget)
        self.frequencyList.setObjectName(_fromUtf8("frequencyList"))
        self.leftVLayout.addWidget(self.frequencyList)
        self.horizontalLayout.addLayout(self.leftVLayout)
        self.rightHLayout = QtGui.QVBoxLayout()
        self.rightHLayout.setObjectName(_fromUtf8("rightHLayout"))
        self.moleculeCanvas = MplCanvas(self.centralwidget)
        self.moleculeCanvas.setMinimumSize(QtCore.QSize(200, 200))
        self.moleculeCanvas.setObjectName(_fromUtf8("moleculeCanvas"))
        self.rightHLayout.addWidget(self.moleculeCanvas)
        self.toolbar = QtGui.QWidget(self.centralwidget)
        self.toolbar.setObjectName(_fromUtf8("toolbar"))
        self.rightHLayout.addWidget(self.toolbar)
        self.spectrumCanvas = MplCanvas(self.centralwidget)
        self.spectrumCanvas.setObjectName(_fromUtf8("spectrumCanvas"))
        self.rightHLayout.addWidget(self.spectrumCanvas)
        self.horizontalLayout.addLayout(self.rightHLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 757, 19))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.fileMenu = QtGui.QMenu(self.menuBar)
        self.fileMenu.setObjectName(_fromUtf8("fileMenu"))
        self.viewMenu = QtGui.QMenu(self.menuBar)
        self.viewMenu.setObjectName(_fromUtf8("viewMenu"))
        self.helpMenu = QtGui.QMenu(self.menuBar)
        self.helpMenu.setObjectName(_fromUtf8("helpMenu"))
        MainWindow.setMenuBar(self.menuBar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.openAction = QtGui.QAction(MainWindow)
        self.openAction.setObjectName(_fromUtf8("openAction"))
        self.saveImageAction = QtGui.QAction(MainWindow)
        self.saveImageAction.setObjectName(_fromUtf8("saveImageAction"))
        self.saveImageAsAction = QtGui.QAction(MainWindow)
        self.saveImageAsAction.setObjectName(_fromUtf8("saveImageAsAction"))
        self.aboutOrbiMolAction = QtGui.QAction(MainWindow)
        self.aboutOrbiMolAction.setObjectName(_fromUtf8("aboutOrbiMolAction"))
        self.quitAction = QtGui.QAction(MainWindow)
        self.quitAction.setObjectName(_fromUtf8("quitAction"))
        self.showIndexAction = QtGui.QAction(MainWindow)
        self.showIndexAction.setCheckable(True)
        self.showIndexAction.setObjectName(_fromUtf8("showIndexAction"))
        self.showSkeletonAction = QtGui.QAction(MainWindow)
        self.showSkeletonAction.setObjectName(_fromUtf8("showSkeletonAction"))
        self.aboutOpenBabelAction = QtGui.QAction(MainWindow)
        self.aboutOpenBabelAction.setObjectName(_fromUtf8("aboutOpenBabelAction"))
        self.aboutAction = QtGui.QAction(MainWindow)
        self.aboutAction.setObjectName(_fromUtf8("aboutAction"))
        self.aboutMplAction = QtGui.QAction(MainWindow)
        self.aboutMplAction.setObjectName(_fromUtf8("aboutMplAction"))
        self.menuBar.addAction(self.fileMenu.menuAction())
        self.menuBar.addAction(self.viewMenu.menuAction())
        self.menuBar.addAction(self.helpMenu.menuAction())
        self.fontSizeLabel.setBuddy(self.fontSizeComboBox)
        self.lineWidthLabel.setBuddy(self.lineWidthComboBox)
        self.colorLabelLabel.setBuddy(self.colorLabelCheckBox)
        self.scalingFactorLabel.setBuddy(self.scalingFactorSpinBox)
        self.thresholdLabel.setBuddy(self.thresholdComboBox)
        self.broadeningLabel.setBuddy(self.broadeningComboBox)
        self.fwhmLabel.setBuddy(self.fwhmDoubleSpinBox)

        self.retranslateUi(MainWindow)
        self.fontSizeComboBox.setCurrentIndex(3)
        self.lineWidthComboBox.setCurrentIndex(3)
        self.thresholdComboBox.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "QVibeplot", None))
        self.moleculeGB.setTitle(_translate("MainWindow", "Molecule display", None))
        self.fontSizeLabel.setText(_translate("MainWindow", "font size", None))
        self.lineWidthLabel.setText(_translate("MainWindow", "linewidth", None))
        self.lineWidthComboBox.setItemText(0, _translate("MainWindow", "0.0", None))
        self.lineWidthComboBox.setItemText(1, _translate("MainWindow", "0.2", None))
        self.lineWidthComboBox.setItemText(2, _translate("MainWindow", "0.5", None))
        self.lineWidthComboBox.setItemText(3, _translate("MainWindow", "1.0", None))
        self.lineWidthComboBox.setItemText(4, _translate("MainWindow", "2.0", None))
        self.lineWidthComboBox.setItemText(5, _translate("MainWindow", "4.0", None))
        self.colorLabelLabel.setText(_translate("MainWindow", "black labels", None))
        self.vibrationGB.setTitle(_translate("MainWindow", "Vibration display", None))
        self.scalingFactorLabel.setText(_translate("MainWindow", "zooming factor", None))
        self.thresholdLabel.setText(_translate("MainWindow", "threshold", None))
        self.spectrumGB.setTitle(_translate("MainWindow", "Spectrum display", None))
        self.broadeningLabel.setText(_translate("MainWindow", "broadening", None))
        self.broadeningComboBox.setItemText(0, _translate("MainWindow", "none", None))
        self.broadeningComboBox.setItemText(1, _translate("MainWindow", "lorentzian", None))
        self.broadeningComboBox.setItemText(2, _translate("MainWindow", "gaussian", None))
        self.fwhmLabel.setText(_translate("MainWindow", "FWHM", None))
        self.frequencyList.setSortingEnabled(True)
        self.fileMenu.setTitle(_translate("MainWindow", "File", None))
        self.viewMenu.setTitle(_translate("MainWindow", "View", None))
        self.helpMenu.setTitle(_translate("MainWindow", "Help", None))
        self.openAction.setText(_translate("MainWindow", "Open", None))
        self.saveImageAction.setText(_translate("MainWindow", "Save image", None))
        self.saveImageAsAction.setText(_translate("MainWindow", "Save image as...", None))
        self.aboutOrbiMolAction.setText(_translate("MainWindow", "About OrbiMol...", None))
        self.quitAction.setText(_translate("MainWindow", "Quit", None))
        self.showIndexAction.setText(_translate("MainWindow", "Show index", None))
        self.showSkeletonAction.setText(_translate("MainWindow", "Show skeleton", None))
        self.aboutOpenBabelAction.setText(_translate("MainWindow", "About Open Babel", None))
        self.aboutAction.setText(_translate("MainWindow", "About", None))
        self.aboutMplAction.setText(_translate("MainWindow", "About Matplotlib", None))

from mpl_canvas import MplCanvas
